services:
  db:
    container_name: transfer-db
    image: postgres:16.2-alpine3.19
    user: 'root'
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: yuji
      POSTGRES_PASSWORD: S3cret
      POSTGRES_DB: transfer_service
    restart: always
